### ISSUE TITLE
Add support to access to generic kubernetes cluster

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/concourse-kpack-resource#8]
Currently, we only support gke & pks clusters. This excludes kpack running on other clusters like TKG. 

We should add the ability to provide access with a generic `kubeconfig`.

**Comment by doddatpivotal** [comment]
I'm interested in this in order to demo pipelines that show Tanzu developer experience.  Concourse, TBS, Harbor, TKG.

**Comment by dumez-k** [comment]
Adressed by: https://github.com/vmware-tanzu/concourse-kpack-resource/pull/12
